Instala as Bibliotecas

In [1]:
# pip install pandas

In [2]:
# pip install sqlalchemy

In [3]:
# pip install psycopg2

Importar as Bibliotecas

In [4]:
import pandas as pd
pd.set_option("display.max_colwidth", 150)
pd.set_option("display.min_rows", 20)

from sqlalchemy import create_engine
from datetime import datetime, timedelta
import time

c:\Users\lucas\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

Definir função para buscar os Dados

In [5]:
def busca_titulos_tesouro_direto():
    url = 'https://www.tesourotransparente.gov.br/ckan/dataset/df56aa42-484a-4a59-8184-7676580c81e3/resource/796d2059-14e9-44e3-80c9-2d9e30b405c1/download/PrecoTaxaTesouroDireto.csv'
    df = pd.read_csv(url, sep=';', decimal=',')
    df['Data_Vencimento'] = pd.to_datetime(df['Data Vencimento'], dayfirst=True)
    df['Data_Base'] = pd.to_datetime(df['Data Base'], dayfirst=True)
    multi_indice = pd.MultiIndex.from_frame(df.iloc[:,:3])
    df = df.set_index(multi_indice).iloc[:, 3:]
    return df

Busca os títulos do Tesouro Direto

In [6]:
titulos = busca_titulos_tesouro_direto()

In [7]:
titulos

                                                                   Taxa Compra Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado                      01/01/2010      09/03/2009              10.46
                                       01/10/2009      09/03/2009              10.64
                                       01/07/2009      09/03/2009              11.01
                                       01/01/2012      09/03/2009              11.19
                                       01/04/2009      09/03/2009              11.75
Tesouro IPCA+ com Juros Semestrais     15/05/2013      09/03/2009               7.00
                                       15/08/2012      09/03/2009               6.92
                                       15/05/2011      09/03/2009               6.70
                                       15/08/2010      09/03/2009               6.43
                                       15/05/2009      09/03/2009               6.84
...                                                                              ...
                                       15/05/2011      26/11/2009               5.67
Tesouro IPCA+                          15/05/2015      26/11/2009               6.82
                                       15/08/2024      26/11/2009               6.54
Tesouro IGPM+ com Juros Semestrais     01/01/2031      26/11/2009               6.57
                                       01/03/2011      26/11/2009               5.43
                                       01/07/2017      26/11/2009               6.43
                                       01/04/2021      26/11/2009               6.63
Tesouro Prefixado com Juros Semestrais 01/01/2011      26/11/2009              10.20
                                       01/01/2012      26/11/2009              11.68
                                       01/01/2013      26/11/2009              12.38

                                                                   Taxa Venda Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado                      01/01/2010      09/03/2009             10.50
                                       01/10/2009      09/03/2009             10.68
                                       01/07/2009      09/03/2009             11.04
                                       01/01/2012      09/03/2009             11.25
                                       01/04/2009      09/03/2009             11.78
Tesouro IPCA+ com Juros Semestrais     15/05/2013      09/03/2009              7.06
                                       15/08/2012      09/03/2009              6.96
                                       15/05/2011      09/03/2009              6.74
                                       15/08/2010      09/03/2009              6.45
                                       15/05/2009      09/03/2009              6.86
...                                                                             ...
                                       15/05/2011      26/11/2009              5.69
Tesouro IPCA+                          15/05/2015      26/11/2009              6.88
                                       15/08/2024      26/11/2009              6.62
Tesouro IGPM+ com Juros Semestrais     01/01/2031      26/11/2009              6.67
                                       01/03/2011      26/11/2009              5.45
                                       01/07/2017      26/11/2009              6.49
                                       01/04/2021      26/11/2009              6.71
Tesouro Prefixado com Juros Semestrais 01/01/2011      26/11/2009             10.24
                                       01/01/2012      26/11/2009             11.74
                                       01/01/2013      26/11/2009             12.44

                                                                   PU Compra Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado                      01/01/2010      09/03/2009           922.25
                                       01/10/2009      09/03/2009           944.61
                                       01/07/2009      09/03/2009           968.58
                                       01/01/2012      09/03/2009           742.60
                                       01/04/2009      09/03/2009           992.97
Tesouro IPCA+ com Juros Semestrais     15/05/2013      09/03/2009          1781.85
                                       15/08/2012      09/03/2009          1767.72
                                       15/05/2011      09/03/2009          1819.31
                                       15/08/2010      09/03/2009          1806.17
                                       15/05/2009      09/03/2009          1840.43
...                                                                            ...
                                       15/05/2011      26/11/2009          1870.13
Tesouro IPCA+                          15/05/2015      26/11/2009          1296.14
                                       15/08/2024      26/11/2009           733.42
Tesouro IGPM+ com Juros Semestrais     01/01/2031      26/11/2009          3630.71
                                       01/03/2011      26/11/2009          2254.47
                                       01/07/2017      26/11/2009          2208.39
                                       01/04/2021      26/11/2009          2125.09
Tesouro Prefixado com Juros Semestrais 01/01/2011      26/11/2009          1037.81
                                       01/01/2012      26/11/2009          1011.13
                                       01/01/2013      26/11/2009           983.59

                                                                   PU Venda Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado                      01/01/2010      09/03/2009          921.98
                                       01/10/2009      09/03/2009          944.42
                                       01/07/2009      09/03/2009          968.50
                                       01/01/2012      09/03/2009          741.48
                                       01/04/2009      09/03/2009          992.95
Tesouro IPCA+ com Juros Semestrais     15/05/2013      09/03/2009         1778.19
                                       15/08/2012      09/03/2009         1765.64
                                       15/05/2011      09/03/2009         1817.92
                                       15/08/2010      09/03/2009         1805.70
                                       15/05/2009      09/03/2009         1840.37
...                                                                           ...
                                       15/05/2011      26/11/2009         1869.63
Tesouro IPCA+                          15/05/2015      26/11/2009         1292.18
                                       15/08/2024      26/11/2009          725.39
Tesouro IGPM+ com Juros Semestrais     01/01/2031      26/11/2009         3596.07
                                       01/03/2011      26/11/2009         2253.95
                                       01/07/2017      26/11/2009         2200.89
                                       01/04/2021      26/11/2009         2112.01
Tesouro Prefixado com Juros Semestrais 01/01/2011      26/11/2009         1037.42
                                       01/01/2012      26/11/2009         1010.12
                                       01/01/2013      26/11/2009          982.21

                                                                   PU Base Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado                      01/01/2010      09/03/2009         921.62
                                       01/10/2009      09/03/2009         944.04
                                       01/07/2009      09/03/2009         968.10
                                       01/01/2012      09/03/2009         741.17
                                       01/04/2009      09/03/2009         992.51
Tesouro IPCA+ com Juros Semestrais     15/05/2013      09/03/2009        1777.34
                                       15/08/2012      09/03/2009        1764.81
                                       15/05/2011      09/03/2009        1817.08
                                       15/08/2010      09/03/2009        1804.88
                                       15/05/2009      09/03/2009        1839.50
...                                                                          ...
                                       15/05/2011      26/11/2009        1869.02
Tesouro IPCA+                          15/05/2015      26/11/2009        1291.70
                                       15/08/2024      26/11/2009         725.13
Tesouro IGPM+ com Juros Semestrais     01/01/2031      26/11/2009        3594.96
                                       01/03/2011      26/11/2009        2253.35
                                       01/07/2017      26/11/2009        2200.22
                                       01/04/2021      26/11/2009        2111.36
Tesouro Prefixado com Juros Semestrais 01/01/2011      26/11/2009        1037.02
                                       01/01/2012      26/11/2009        1009.67
                                       01/01/2013      26/11/2009         981.76

                                                                  Data_Vencimento  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado                      01/01/2010      09/03/2009      2010-01-01
                                       01/10/2009      09/03/2009      2009-10-01
                                       01/07/2009      09/03/2009      2009-07-01
                                       01/01/2012      09/03/2009      2012-01-01
                                       01/04/2009      09/03/2009      2009-04-01
Tesouro IPCA+ com Juros Semestrais     15/05/2013      09/03/2009      2013-05-15
                                       15/08/2012      09/03/2009      2012-08-15
                                       15/05/2011      09/03/2009      2011-05-15
                                       15/08/2010      09/03/2009      2010-08-15
                                       15/05/2009      09/03/2009      2009-05-15
...                                                                           ...
                                       15/05/2011      26/11/2009      2011-05-15
Tesouro IPCA+                          15/05/2015      26/11/2009      2015-05-15
                                       15/08/2024      26/11/2009      2024-08-15
Tesouro IGPM+ com Juros Semestrais     01/01/2031      26/11/2009      2031-01-01
                                       01/03/2011      26/11/2009      2011-03-01
                                       01/07/2017      26/11/2009      2017-07-01
                                       01/04/2021      26/11/2009      2021-04-01
Tesouro Prefixado com Juros Semestrais 01/01/2011      26/11/2009      2011-01-01
                                       01/01/2012      26/11/2009      2012-01-01
                                       01/01/2013      26/11/2009      2013-01-01

                                                                   Data_Base
Tipo Titulo                            Data Vencimento Data Base
Tesouro Prefixado                      01/01/2010      09/03/2009 2009-03-09
                                       01/10/2009      09/03/2009 2009-03-09
                                       01/07/2009      09/03/2009 2009-03-09
                                       01/01/2012      09/03/2009 2009-03-09
                                       01/04/2009      09/03/2009 2009-03-09
Tesouro IPCA+ com Juros Semestrais     15/05/2013      09/03/2009 2009-03-09
                                       15/08/2012      09/03/2009 2009-03-09
                                       15/05/2011      09/03/2009 2009-03-09
                                       15/08/2010      09/03/2009 2009-03-09
                                       15/05/2009      09/03/2009 2009-03-09
...                                                                      ...
                                       15/05/2011      26/11/2009 2009-11-26
Tesouro IPCA+                          15/05/2015      26/11/2009 2009-11-26
                                       15/08/2024      26/11/2009 2009-11-26
Tesouro IGPM+ com Juros Semestrais     01/01/2031      26/11/2009 2009-11-26
                                       01/03/2011      26/11/2009 2009-11-26
                                       01/07/2017      26/11/2009 2009-11-26
                                       01/04/2021      26/11/2009 2009-11-26
Tesouro Prefixado com Juros Semestrais 01/01/2011      26/11/2009 2009-11-26
                                       01/01/2012      26/11/2009 2009-11-26
                                       01/01/2013      26/11/2009 2009-11-26

[164235 rows x 7 columns]

Busca somente os Préfixados

In [8]:
prefixado = titulos.loc[('Tesouro Prefixado')]
prefixado['Tipo'] = "PRE-FIXADOS"

C:\Users\lucas\AppData\Local\Temp\ipykernel_22328\2914005242.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prefixado['Tipo'] = "PRE-FIXADOS"

In [9]:
prefixado

,,Taxa Compra Manha,Taxa Venda Manha,PU Compra Manha,PU Venda Manha,PU Base Manha,Data_Vencimento,Data_Base,Tipo
Data Vencimento,Data Base,,,,,,,,
01/01/2010,09/03/2009,10.46,10.50,922.25,921.98,921.62,2010-01-01,2009-03-09,PRE-FIXADOS
01/10/2009,09/03/2009,10.64,10.68,944.61,944.42,944.04,2009-10-01,2009-03-09,PRE-FIXADOS
01/07/2009,09/03/2009,11.01,11.04,968.58,968.50,968.10,2009-07-01,2009-03-09,PRE-FIXADOS
01/01/2012,09/03/2009,11.19,11.25,742.60,741.48,741.17,2012-01-01,2009-03-09,PRE-FIXADOS
01/04/2009,09/03/2009,11.75,11.78,992.97,992.95,992.51,2009-04-01,2009-03-09,PRE-FIXADOS
01/07/2010,06/03/2009,10.79,10.83,874.78,874.37,874.01,2010-07-01,2009-03-06,PRE-FIXADOS
01/01/2011,06/03/2009,11.05,11.10,826.89,826.22,825.87,2011-01-01,2009-03-06,PRE-FIXADOS
01/01/2012,06/03/2009,11.35,11.41,739.30,738.18,737.86,2012-01-01,2009-03-06,PRE-FIXADOS
01/10/2009,06/03/2009,10.89,10.93,943.02,942.83,942.44,2009-10-01,2009-03-06,PRE-FIXADOS
01/07/2009,06/03/2009,11.23,11.26,967.59,967.51,967.10,2009-07-01,2009-03-06,PRE-FIXADOS
...,...,...,...,...,...,...,...,...,...
01/01/2011,30/11/2009,10.28,10.32,899.41,899.06,898.71,2011-01-01,2009-11-30,PRE-FIXADOS
01/01/2012,30/11/2009,11.81,11.87,792.85,791.96,791.61,2012-01-01,2009-11-30,PRE-FIXADOS
01/01/2010,27/11/2009,8.66,8.69,992.44,992.42,992.09,2010-01-01,2009-11-27,PRE-FIXADOS
01/07/2010,27/11/2009,9.11,9.15,950.74,950.53,950.20,2010-07-01,2009-11-27,PRE-FIXADOS
01/01/2012,27/11/2009,11.78,11.84,792.94,792.05,791.70,2012-01-01,2009-11-27,PRE-FIXADOS
01/01/2011,27/11/2009,10.26,10.30,899.24,898.89,898.54,2011-01-01,2009-11-27,PRE-FIXADOS
01/01/2010,26/11/2009,8.64,8.67,992.13,992.11,991.78,2010-01-01,2009-11-26,PRE-FIXADOS
01/07/2010,26/11/2009,9.05,9.09,950.71,950.51,950.18,2010-07-01,2009-11-26,PRE-FIXADOS
01/01/2011,26/11/2009,10.18,10.22,899.61,899.25,898.90,2011-01-01,2009-11-26,PRE-FIXADOS
01/01/2012,26/11/2009,11.64,11.70,794.66,793.77,793.42,2012-01-01,2009-11-26,PRE-FIXADOS

In [10]:
for i, row in prefixado.iterrows():
    ifor_val = datetime.now() - timedelta(hours=1, minutes=0)
    prefixado.at[i,'dt_update'] = ifor_val
    time.sleep(1/10000)

C:\Users\lucas\AppData\Local\Temp\ipykernel_22328\913561871.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prefixado.at[i,'dt_update'] = ifor_val

In [11]:
prefixado

,,Taxa Compra Manha,Taxa Venda Manha,PU Compra Manha,PU Venda Manha,PU Base Manha,Data_Vencimento,Data_Base,Tipo,dt_update
Data Vencimento,Data Base,,,,,,,,,
01/01/2010,09/03/2009,10.46,10.50,922.25,921.98,921.62,2010-01-01,2009-03-09,PRE-FIXADOS,2025-11-21 16:16:33.812669
01/10/2009,09/03/2009,10.64,10.68,944.61,944.42,944.04,2009-10-01,2009-03-09,PRE-FIXADOS,2025-11-21 16:16:33.845074
01/07/2009,09/03/2009,11.01,11.04,968.58,968.50,968.10,2009-07-01,2009-03-09,PRE-FIXADOS,2025-11-21 16:16:33.860217
01/01/2012,09/03/2009,11.19,11.25,742.60,741.48,741.17,2012-01-01,2009-03-09,PRE-FIXADOS,2025-11-21 16:16:33.875677
01/04/2009,09/03/2009,11.75,11.78,992.97,992.95,992.51,2009-04-01,2009-03-09,PRE-FIXADOS,2025-11-21 16:16:33.890677
01/07/2010,06/03/2009,10.79,10.83,874.78,874.37,874.01,2010-07-01,2009-03-06,PRE-FIXADOS,2025-11-21 16:16:33.906826
01/01/2011,06/03/2009,11.05,11.10,826.89,826.22,825.87,2011-01-01,2009-03-06,PRE-FIXADOS,2025-11-21 16:16:33.922343
01/01/2012,06/03/2009,11.35,11.41,739.30,738.18,737.86,2012-01-01,2009-03-06,PRE-FIXADOS,2025-11-21 16:16:33.939250
01/10/2009,06/03/2009,10.89,10.93,943.02,942.83,942.44,2009-10-01,2009-03-06,PRE-FIXADOS,2025-11-21 16:16:33.954768
01/07/2009,06/03/2009,11.23,11.26,967.59,967.51,967.10,2009-07-01,2009-03-06,PRE-FIXADOS,2025-11-21 16:16:33.969304
...,...,...,...,...,...,...,...,...,...,...
01/01/2011,30/11/2009,10.28,10.32,899.41,899.06,898.71,2011-01-01,2009-11-30,PRE-FIXADOS,2025-11-21 16:23:37.884716
01/01/2012,30/11/2009,11.81,11.87,792.85,791.96,791.61,2012-01-01,2009-11-30,PRE-FIXADOS,2025-11-21 16:23:37.899894
01/01/2010,27/11/2009,8.66,8.69,992.44,992.42,992.09,2010-01-01,2009-11-27,PRE-FIXADOS,2025-11-21 16:23:37.915549
01/07/2010,27/11/2009,9.11,9.15,950.74,950.53,950.20,2010-07-01,2009-11-27,PRE-FIXADOS,2025-11-21 16:23:37.931846
01/01/2012,27/11/2009,11.78,11.84,792.94,792.05,791.70,2012-01-01,2009-11-27,PRE-FIXADOS,2025-11-21 16:23:37.946517
01/01/2011,27/11/2009,10.26,10.30,899.24,898.89,898.54,2011-01-01,2009-11-27,PRE-FIXADOS,2025-11-21 16:23:37.961485
01/01/2010,26/11/2009,8.64,8.67,992.13,992.11,991.78,2010-01-01,2009-11-26,PRE-FIXADOS,2025-11-21 16:23:37.977255
01/07/2010,26/11/2009,9.05,9.09,950.71,950.51,950.18,2010-07-01,2009-11-26,PRE-FIXADOS,2025-11-21 16:23:37.992436
01/01/2011,26/11/2009,10.18,10.22,899.61,899.25,898.90,2011-01-01,2009-11-26,PRE-FIXADOS,2025-11-21 16:23:38.007624
01/01/2012,26/11/2009,11.64,11.70,794.66,793.77,793.42,2012-01-01,2009-11-26,PRE-FIXADOS,2025-11-21 16:23:38.023145

Busca os IPCAs

In [12]:
ipca = titulos.loc[('Tesouro IPCA+')]
ipca['Tipo'] = "IPCA"

C:\Users\lucas\AppData\Local\Temp\ipykernel_22328\3738600803.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ipca['Tipo'] = "IPCA"

In [13]:
for i, row in ipca.iterrows():
    ifor_val = datetime.now() - timedelta(hours=1, minutes=0)
    ipca.at[i,'dt_update'] = ifor_val
    time.sleep(1/10000)

C:\Users\lucas\AppData\Local\Temp\ipykernel_22328\3161604202.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ipca.at[i,'dt_update'] = ifor_val

In [14]:
ipca

                            Taxa Compra Manha  Taxa Venda Manha  \
Data Vencimento Data Base
15/08/2024      09/03/2009               6.97              7.05
15/05/2015      09/03/2009               7.18              7.24
                06/03/2009               7.24              7.30
15/08/2024      06/03/2009               6.98              7.06
15/05/2015      20/02/2009               7.53              7.59
15/08/2024      20/02/2009               6.87              6.95
                19/02/2009               6.87              6.95
15/05/2015      19/02/2009               7.60              7.66
                16/02/2009               7.58              7.64
15/08/2024      16/02/2009               6.93              7.01
...                                       ...               ...
15/05/2015      31/08/2009               6.45              6.51
15/08/2024      31/08/2009               6.29              6.37
                28/08/2009               6.29              6.37
15/05/2015      28/08/2009               6.42              6.48
                30/11/2009               6.83              6.89
15/08/2024      30/11/2009               6.56              6.64
15/05/2015      27/11/2009               6.84              6.90
15/08/2024      27/11/2009               6.56              6.64
15/05/2015      26/11/2009               6.82              6.88
15/08/2024      26/11/2009               6.54              6.62

                            PU Compra Manha  PU Venda Manha  PU Base Manha  \
Data Vencimento Data Base
15/08/2024      09/03/2009           641.68          634.34         634.04
15/05/2015      09/03/2009          1179.49         1175.43        1174.86
                06/03/2009          1174.86         1170.81        1169.76
15/08/2024      06/03/2009           640.45          633.13         632.57
15/05/2015      20/02/2009          1150.18         1146.20        1144.57
15/08/2024      20/02/2009           647.83          640.40         639.50
                19/02/2009           646.92          639.50         639.18
15/05/2015      19/02/2009          1143.91         1139.96        1139.36
                16/02/2009          1143.45         1139.49        1138.90
15/08/2024      16/02/2009           640.40          633.05         632.73
...                                     ...             ...            ...
15/05/2015      31/08/2009          1292.45         1288.31        1287.91
15/08/2024      31/08/2009           743.05          734.76         734.54
                28/08/2009           742.82          734.54         734.22
15/05/2015      28/08/2009          1294.12         1289.97        1289.40
                30/11/2009          1297.26         1293.30        1292.79
15/08/2024      30/11/2009           732.39          724.38         724.10
15/05/2015      27/11/2009          1296.09         1292.13        1291.27
15/08/2024      27/11/2009           732.11          724.10         723.63
15/05/2015      26/11/2009          1296.14         1292.18        1291.70
15/08/2024      26/11/2009           733.42          725.39         725.13

                           Data_Vencimento  Data_Base  Tipo  \
Data Vencimento Data Base
15/08/2024      09/03/2009      2024-08-15 2009-03-09  IPCA
15/05/2015      09/03/2009      2015-05-15 2009-03-09  IPCA
                06/03/2009      2015-05-15 2009-03-06  IPCA
15/08/2024      06/03/2009      2024-08-15 2009-03-06  IPCA
15/05/2015      20/02/2009      2015-05-15 2009-02-20  IPCA
15/08/2024      20/02/2009      2024-08-15 2009-02-20  IPCA
                19/02/2009      2024-08-15 2009-02-19  IPCA
15/05/2015      19/02/2009      2015-05-15 2009-02-19  IPCA
                16/02/2009      2015-05-15 2009-02-16  IPCA
15/08/2024      16/02/2009      2024-08-15 2009-02-16  IPCA
...                                    ...        ...   ...
15/05/2015      31/08/2009      2015-05-15 2009-08-31  IPCA
15/08/2024      31/08/2009      2024-08-15 2009-08-31  IPCA
                28/08/2009      2024-08-15 2009-08-28  IPCA
15/05/2015      28/08/2009      2015-05-15 2009-08-28  IPCA
                30/11/2009      2015-05-15 2009-11-30  IPCA
15/08/2024      30/11/2009      2024-08-15 2009-11-30  IPCA
15/05/2015      27/11/2009      2015-05-15 2009-11-27  IPCA
15/08/2024      27/11/2009      2024-08-15 2009-11-27  IPCA
15/05/2015      26/11/2009      2015-05-15 2009-11-26  IPCA
15/08/2024      26/11/2009      2024-08-15 2009-11-26  IPCA

                                            dt_update
Data Vencimento Data Base
15/08/2024      09/03/2009 2025-11-21 16:23:38.378003
15/05/2015      09/03/2009 2025-11-21 16:23:38.396085
                06/03/2009 2025-11-21 16:23:38.413286
15/08/2024      06/03/2009 2025-11-21 16:23:38.427287
15/05/2015      20/02/2009 2025-11-21 16:23:38.441982
15/08/2024      20/02/2009 2025-11-21 16:23:38.456831
                19/02/2009 2025-11-21 16:23:38.471987
15/05/2015      19/02/2009 2025-11-21 16:23:38.488048
                16/02/2009 2025-11-21 16:23:38.503280
15/08/2024      16/02/2009 2025-11-21 16:23:38.518989
...                                               ...
15/05/2015      31/08/2009 2025-11-21 16:28:17.519020
15/08/2024      31/08/2009 2025-11-21 16:28:17.531392
                28/08/2009 2025-11-21 16:28:17.547040
15/05/2015      28/08/2009 2025-11-21 16:28:17.562771
                30/11/2009 2025-11-21 16:28:17.578872
15/08/2024      30/11/2009 2025-11-21 16:28:17.594529
15/05/2015      27/11/2009 2025-11-21 16:28:17.609706
15/08/2024      27/11/2009 2025-11-21 16:28:17.625109
15/05/2015      26/11/2009 2025-11-21 16:28:17.640448
15/08/2024      26/11/2009 2025-11-21 16:28:17.656364

[17470 rows x 9 columns]

In [15]:
#frames = [prefixado, ipca]
#todos = pd.concat(frames)
ipca = ipca.rename(columns={"Data Vencimento": "DataVencimento", "Data Base": "Data_Base", "Taxa Compra Manha": "CompraManha", "Taxa Venda Manha": "VendaManha", "PU Compra Manha": "PUCompraManha", "PU Venda Manha": "PUVendaManha",  "PU Base Manha": "PUBaseManha"})
prefixado = prefixado.rename(columns={"Data Vencimento": "DataVencimento", "Data Base": "Data_Base", "Taxa Compra Manha": "CompraManha", "Taxa Venda Manha": "VendaManha", "PU Compra Manha": "PUCompraManha", "PU Venda Manha": "PUVendaManha",  "PU Base Manha": "PUBaseManha"})

In [16]:
ipca

                            CompraManha  VendaManha  PUCompraManha  \
Data Vencimento Data Base
15/08/2024      09/03/2009         6.97        7.05         641.68
15/05/2015      09/03/2009         7.18        7.24        1179.49
                06/03/2009         7.24        7.30        1174.86
15/08/2024      06/03/2009         6.98        7.06         640.45
15/05/2015      20/02/2009         7.53        7.59        1150.18
15/08/2024      20/02/2009         6.87        6.95         647.83
                19/02/2009         6.87        6.95         646.92
15/05/2015      19/02/2009         7.60        7.66        1143.91
                16/02/2009         7.58        7.64        1143.45
15/08/2024      16/02/2009         6.93        7.01         640.40
...                                 ...         ...            ...
15/05/2015      31/08/2009         6.45        6.51        1292.45
15/08/2024      31/08/2009         6.29        6.37         743.05
                28/08/2009         6.29        6.37         742.82
15/05/2015      28/08/2009         6.42        6.48        1294.12
                30/11/2009         6.83        6.89        1297.26
15/08/2024      30/11/2009         6.56        6.64         732.39
15/05/2015      27/11/2009         6.84        6.90        1296.09
15/08/2024      27/11/2009         6.56        6.64         732.11
15/05/2015      26/11/2009         6.82        6.88        1296.14
15/08/2024      26/11/2009         6.54        6.62         733.42

                            PUVendaManha  PUBaseManha Data_Vencimento  \
Data Vencimento Data Base
15/08/2024      09/03/2009        634.34       634.04      2024-08-15
15/05/2015      09/03/2009       1175.43      1174.86      2015-05-15
                06/03/2009       1170.81      1169.76      2015-05-15
15/08/2024      06/03/2009        633.13       632.57      2024-08-15
15/05/2015      20/02/2009       1146.20      1144.57      2015-05-15
15/08/2024      20/02/2009        640.40       639.50      2024-08-15
                19/02/2009        639.50       639.18      2024-08-15
15/05/2015      19/02/2009       1139.96      1139.36      2015-05-15
                16/02/2009       1139.49      1138.90      2015-05-15
15/08/2024      16/02/2009        633.05       632.73      2024-08-15
...                                  ...          ...             ...
15/05/2015      31/08/2009       1288.31      1287.91      2015-05-15
15/08/2024      31/08/2009        734.76       734.54      2024-08-15
                28/08/2009        734.54       734.22      2024-08-15
15/05/2015      28/08/2009       1289.97      1289.40      2015-05-15
                30/11/2009       1293.30      1292.79      2015-05-15
15/08/2024      30/11/2009        724.38       724.10      2024-08-15
15/05/2015      27/11/2009       1292.13      1291.27      2015-05-15
15/08/2024      27/11/2009        724.10       723.63      2024-08-15
15/05/2015      26/11/2009       1292.18      1291.70      2015-05-15
15/08/2024      26/11/2009        725.39       725.13      2024-08-15

                            Data_Base  Tipo                  dt_update
Data Vencimento Data Base
15/08/2024      09/03/2009 2009-03-09  IPCA 2025-11-21 16:23:38.378003
15/05/2015      09/03/2009 2009-03-09  IPCA 2025-11-21 16:23:38.396085
                06/03/2009 2009-03-06  IPCA 2025-11-21 16:23:38.413286
15/08/2024      06/03/2009 2009-03-06  IPCA 2025-11-21 16:23:38.427287
15/05/2015      20/02/2009 2009-02-20  IPCA 2025-11-21 16:23:38.441982
15/08/2024      20/02/2009 2009-02-20  IPCA 2025-11-21 16:23:38.456831
                19/02/2009 2009-02-19  IPCA 2025-11-21 16:23:38.471987
15/05/2015      19/02/2009 2009-02-19  IPCA 2025-11-21 16:23:38.488048
                16/02/2009 2009-02-16  IPCA 2025-11-21 16:23:38.503280
15/08/2024      16/02/2009 2009-02-16  IPCA 2025-11-21 16:23:38.518989
...                               ...   ...                        ...
15/05/2015      31/08/2009 2009-08-31  IPCA 2025-11-21 16:28:17.519020
15/08/2024      31/08/2009 2009-08-31  IPCA 2025-11-21 16:28:17.531392
                28/08/2009 2009-08-28  IPCA 2025-11-21 16:28:17.547040
15/05/2015      28/08/2009 2009-08-28  IPCA 2025-11-21 16:28:17.562771
                30/11/2009 2009-11-30  IPCA 2025-11-21 16:28:17.578872
15/08/2024      30/11/2009 2009-11-30  IPCA 2025-11-21 16:28:17.594529
15/05/2015      27/11/2009 2009-11-27  IPCA 2025-11-21 16:28:17.609706
15/08/2024      27/11/2009 2009-11-27  IPCA 2025-11-21 16:28:17.625109
15/05/2015      26/11/2009 2009-11-26  IPCA 2025-11-21 16:28:17.640448
15/08/2024      26/11/2009 2009-11-26  IPCA 2025-11-21 16:28:17.656364

[17470 rows x 9 columns]

Grava os dados no Banco de Dados

In [17]:
connection_string = "postgresql://postgres:postgres@localhost:5432/postgres"

In [18]:
engine = create_engine(connection_string)

In [19]:
ipca.to_sql("dadostesouroipca", con=engine, if_exists="append", index=False)
prefixado.to_sql("dadostesouropre", con=engine, if_exists="append", index=False)

74

Limpando os dados para Camada Gold

In [24]:
pip install "flask<2.3,>=2.2"

Requirement already satisfied: flask<2.3,>=2.2 in c:\users\lucas\anaconda3\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: click>=8.0 in c:\users\lucas\anaconda3\lib\site-packages (from flask<2.3,>=2.2) (8.3.0)
Requirement already satisfied: Werkzeug>=2.2.2 in c:\users\lucas\anaconda3\lib\site-packages (from flask<2.3,>=2.2) (2.2.2)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\lucas\anaconda3\lib\site-packages (from flask<2.3,>=2.2) (2.0.1)
Requirement already satisfied: Jinja2>=3.0 in c:\users\lucas\anaconda3\lib\site-packages (from flask<2.3,>=2.2) (3.1.6)
Requirement already satisfied: colorama in c:\users\lucas\anaconda3\lib\site-packages (from click>=8.0->flask<2.3,>=2.2) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\lucas\anaconda3\lib\site-packages (from Jinja2>=3.0->flask<2.3,>=2.2) (2.1.1)

In [25]:
pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\lucas\anaconda3\lib\site-packages (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [26]:
pip install pyspark boto3

Requirement already satisfied: pyspark in c:\users\lucas\anaconda3\lib\site-packages (4.0.1)
Requirement already satisfied: boto3 in c:\users\lucas\anaconda3\lib\site-packages (1.41.1)
Requirement already satisfied: py4j==0.10.9.9 in c:\users\lucas\anaconda3\lib\site-packages (from pyspark) (0.10.9.9)
Requirement already satisfied: botocore<1.42.0,>=1.41.1 in c:\users\lucas\anaconda3\lib\site-packages (from boto3) (1.41.1)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\lucas\anaconda3\lib\site-packages (from boto3) (0.10.0)
Requirement already satisfied: s3transfer<0.16.0,>=0.15.0 in c:\users\lucas\anaconda3\lib\site-packages (from boto3) (0.15.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\lucas\anaconda3\lib\site-packages (from botocore<1.42.0,>=1.41.1->boto3) (2.5.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\lucas\anaconda3\lib\site-packages (from botocore<1.42.0,>=1.41.1->boto3) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\lucas\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.42.0,>=1.41.1->boto3) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import os
from pyspark.sql.functions import col, from_unixtime, avg, count
from dotenv import load_dotenv
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Desafio Final") \
    .getOrCreate()

In [35]:
df_bronze_ipca = spark.createDataFrame(ipca)
df_bronze_pre = spark.createDataFrame(prefixado)

df_bronze_ipca.show()
df_bronze_pre.show()

+-----------+----------+-------------+------------+-----------+-------------------+-------------------+----+--------------------+
|CompraManha|VendaManha|PUCompraManha|PUVendaManha|PUBaseManha|    Data_Vencimento|          Data_Base|Tipo|           dt_update|
+-----------+----------+-------------+------------+-----------+-------------------+-------------------+----+--------------------+
|       6.97|      7.05|       641.68|      634.34|     634.04|2024-08-15 00:00:00|2009-03-09 00:00:00|IPCA|2025-11-21 16:23:...|
|       7.18|      7.24|      1179.49|     1175.43|    1174.86|2015-05-15 00:00:00|2009-03-09 00:00:00|IPCA|2025-11-21 16:23:...|
|       7.24|       7.3|      1174.86|     1170.81|    1169.76|2015-05-15 00:00:00|2009-03-06 00:00:00|IPCA|2025-11-21 16:23:...|
|       6.98|      7.06|       640.45|      633.13|     632.57|2024-08-15 00:00:00|2009-03-06 00:00:00|IPCA|2025-11-21 16:23:...|
|       7.53|      7.59|      1150.18|      1146.2|    1144.57|2015-05-15 00:00:00|2009-02-20 00:00:00|IPCA|2025-11-21 16:23:...|
|       6.87|      6.95|       647.83|       640.4|      639.5|2024-08-15 00:00:00|2009-02-20 00:00:00|IPCA|2025-11-21 16:23:...|
|       6.87|      6.95|       646.92|       639.5|     639.18|2024-08-15 00:00:00|2009-02-19 00:00:00|IPCA|2025-11-21 16:23:...|
|        7.6|      7.66|      1143.91|     1139.96|    1139.36|2015-05-15 00:00:00|2009-02-19 00:00:00|IPCA|2025-11-21 16:23:...|
|       7.58|      7.64|      1143.45|     1139.49|     1138.9|2015-05-15 00:00:00|2009-02-16 00:00:00|IPCA|2025-11-21 16:23:...|
|       6.93|      7.01|        640.4|      633.05|     632.73|2024-08-15 00:00:00|2009-02-16 00:00:00|IPCA|2025-11-21 16:23:...|
|        7.7|      7.76|      1134.96|     1131.03|    1129.92|2015-05-15 00:00:00|2009-02-13 00:00:00|IPCA|2025-11-21 16:23:...|
|       6.97|      7.05|        636.4|      629.09|      628.5|2024-08-15 00:00:00|2009-02-13 00:00:00|IPCA|2025-11-21 16:23:...|
|       6.93|      7.01|       639.57|      632.23|     631.96|2024-08-15 00:00:00|2009-02-12 00:00:00|IPCA|2025-11-21 16:23:...|
|       7.61|      7.67|      1139.93|     1135.98|    1135.48|2015-05-15 00:00:00|2009-02-12 00:00:00|IPCA|2025-11-21 16:23:...|
|       6.88|      6.96|       645.67|      638.26|     637.95|2024-08-15 00:00:00|2009-02-18 00:00:00|IPCA|2025-11-21 16:23:...|
|       7.59|      7.65|      1143.97|     1140.02|    1139.43|2015-05-15 00:00:00|2009-02-18 00:00:00|IPCA|2025-11-21 16:23:...|
|       7.57|      7.63|       1144.7|     1140.74|    1140.15|2015-05-15 00:00:00|2009-02-17 00:00:00|IPCA|2025-11-21 16:23:...|
|       6.89|      6.97|       644.42|      637.03|     636.71|2024-08-15 00:00:00|2009-02-17 00:00:00|IPCA|2025-11-21 16:23:...|
|       7.36|      7.42|      1165.73|     1161.71|    1161.15|2015-05-15 00:00:00|2009-03-05 00:00:00|IPCA|2025-11-21 16:23:...|
|       6.98|      7.06|       639.88|      632.57|     632.26|2024-08-15 00:00:00|2009-03-05 00:00:00|IPCA|2025-11-21 16:23:...|
+-----------+----------+-------------+------------+-----------+-------------------+-------------------+----+--------------------+
only showing top 20 rows
+-----------+----------+-------------+------------+-----------+-------------------+-------------------+-----------+--------------------+
|CompraManha|VendaManha|PUCompraManha|PUVendaManha|PUBaseManha|    Data_Vencimento|          Data_Base|       Tipo|           dt_update|
+-----------+----------+-------------+------------+-----------+-------------------+-------------------+-----------+--------------------+
|      10.46|      10.5|       922.25|      921.98|     921.62|2010-01-01 00:00:00|2009-03-09 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      10.64|     10.68|       944.61|      944.42|     944.04|2009-10-01 00:00:00|2009-03-09 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      11.01|     11.04|       968.58|       968.5|      968.1|2009-07-01 00:00:00|2009-03-09 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      11.19|     11.25|        742.6|      741.48|     741.17|2012-01-01 00:00:00|2009-03-09 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      11.75|     11.78|       992.97|      992.95|     992.51|2009-04-01 00:00:00|2009-03-09 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      10.79|     10.83|       874.78|      874.37|     874.01|2010-07-01 00:00:00|2009-03-06 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      11.05|      11.1|       826.89|      826.22|     825.87|2011-01-01 00:00:00|2009-03-06 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      11.35|     11.41|        739.3|      738.18|     737.86|2012-01-01 00:00:00|2009-03-06 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      10.89|     10.93|       943.02|      942.83|     942.44|2009-10-01 00:00:00|2009-03-06 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      11.23|     11.26|       967.59|      967.51|      967.1|2009-07-01 00:00:00|2009-03-06 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      10.71|     10.75|       920.19|      919.92|     919.54|2010-01-01 00:00:00|2009-03-06 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      11.86|     11.89|       992.46|      992.44|      992.0|2009-04-01 00:00:00|2009-03-06 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      11.15|      11.2|        825.2|      824.52|     824.18|2011-01-01 00:00:00|2009-03-05 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      11.47|     11.53|       736.75|      735.63|     735.31|2012-01-01 00:00:00|2009-03-05 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      10.77|     10.81|       919.41|      919.13|     918.76|2010-01-01 00:00:00|2009-03-05 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      10.94|     10.98|        942.4|       942.2|     941.81|2009-10-01 00:00:00|2009-03-05 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      11.27|      11.3|       967.07|      966.99|     966.58|2009-07-01 00:00:00|2009-03-05 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      10.88|     10.92|        873.5|      873.08|     872.72|2010-07-01 00:00:00|2009-03-05 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      11.92|     11.95|       991.98|      991.96|     991.52|2009-04-01 00:00:00|2009-03-05 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
|      12.19|     12.22|       988.65|      988.62|     988.17|2009-04-01 00:00:00|2009-02-20 00:00:00|PRE-FIXADOS|2025-11-21 16:16:...|
+-----------+----------+-------------+------------+-----------+-------------------+-------------------+-----------+--------------------+
only showing top 20 rows

In [ ]:
# -----------------------
# Tratamento dos Dados - Camada Silver
# -----------------------
from pyspark.sql.functions import date_format, col


# Remover duplicações e converter timestamps para datas legíveis
df_silver_ipca = df_bronze_ipca.dropDuplicates()
df_silver_pre = df_bronze_pre.drop_duplicates()

# Tratar timestamps e converter para formato legível
df_silver_ipca = df_silver_ipca.withColumn("Data_Vencimento", date_format(col("Data_Vencimento"), "yyyy-MM-dd")) \
                     .withColumn("Data_Base", date_format(col("Data_Base"), "yyyy-MM-dd")) \
                     .withColumn("dt_update", date_format(col("dt_update"), "yyyy-MM-dd HH:mm:ss"))

df_silver_pre = df_silver_pre.withColumn("Data_Vencimento", date_format(col("Data_Vencimento"), "yyyy-MM-dd")) \
                     .withColumn("Data_Base", date_format(col("Data_Base"), "yyyy-MM-dd")) \
                     .withColumn("dt_update", date_format(col("dt_update"), "yyyy-MM-dd HH:mm:ss"))

# Tratar valores nulos
df_silver_ipca = df_silver_ipca.fillna({
    "PUCompraManha": 0,
    "PUVendaManha": 0,
    "PUBaseManha": 0
})

df_silver_pre = df_silver_pre.fillna({
    "PUCompraManha": 0,
    "PUVendaManha": 0,
    "PUBaseManha": 0
})

# Visualizar os dados transformados
print("Dados Transformados do IPCA (Silver):")
df_silver_ipca.show(truncate=False)

print("Dados Transformados do Pré-fixado (Silver):")
df_silver_pre.show(truncate=False)

Dados Transformados (Silver):
+-----------+----------+-------------+------------+-----------+---------------+----------+----+-------------------+
|CompraManha|VendaManha|PUCompraManha|PUVendaManha|PUBaseManha|Data_Vencimento|Data_Base |Tipo|dt_update          |
+-----------+----------+-------------+------------+-----------+---------------+----------+----+-------------------+
|7.06       |7.14      |635.57       |628.32      |628.09     |2024-08-15     |2009-03-19|IPCA|2025-11-21 16:23:39|
|7.46       |7.54      |582.3        |575.58      |575.32     |2024-08-15     |2008-12-18|IPCA|2025-11-21 16:23:42|
|8.79       |8.87      |320.39       |316.01      |315.79     |2024-08-15     |2005-11-01|IPCA|2025-11-21 16:23:44|
|7.91       |7.97      |1042.3       |1038.35     |1037.27    |2015-05-15     |2008-07-11|IPCA|2025-11-21 16:23:45|
|6.36       |6.44      |594.08       |586.64      |586.45     |2024-08-15     |2007-10-22|IPCA|2025-11-21 16:23:51|
|6.97       |7.03      |983.51       |979.25      |978.91     |2015-05-15     |2007-08-09|IPCA|2025-11-21 16:23:53|
|8.64       |8.7       |719.91       |716.19      |715.71     |2015-05-15     |2005-12-16|IPCA|2025-11-21 16:23:59|
|9.72       |9.78      |705.12       |701.73      |701.43     |2015-05-15     |2006-07-17|IPCA|2025-11-21 16:24:07|
|7.29       |7.41      |1535.75      |1509.17     |1509.17    |2040-08-15     |2025-04-16|IPCA|2025-11-21 16:24:14|
|7.14       |7.26      |788.27       |765.99      |765.99     |2050-08-15     |2025-04-07|IPCA|2025-11-21 16:24:17|
|5.97       |6.09      |4315.49      |4313.95     |4313.95    |2024-08-15     |2024-08-14|IPCA|2025-11-21 16:24:17|
|6.69       |6.81      |3869.95      |3860.49     |3860.49    |2026-08-15     |2024-10-28|IPCA|2025-11-21 16:24:19|
|5.75       |5.87      |1291.31      |1260.27     |1260.27    |2045-05-15     |2024-02-08|IPCA|2025-11-21 16:24:30|
|5.74       |5.86      |3039.11      |3018.94     |3018.94    |2029-05-15     |2023-10-05|IPCA|2025-11-21 16:24:38|
|5.39       |5.51      |1324.8       |1292.07     |1292.07    |2045-05-15     |2023-08-18|IPCA|2025-11-21 16:24:39|
|5.86       |5.98      |3554.03      |3541.8      |3541.8     |2026-08-15     |2023-11-09|IPCA|2025-11-21 16:24:40|
|8.74       |8.8       |684.56       |680.92      |680.65     |2015-05-15     |2005-08-31|IPCA|2025-11-21 16:23:40|
|6.77       |6.85      |584.05       |576.93      |576.68     |2024-08-15     |2008-03-10|IPCA|2025-11-21 16:23:46|
|6.9        |6.98      |607.39       |600.18      |599.92     |2024-08-15     |2008-08-11|IPCA|2025-11-21 16:23:47|
|7.85       |7.91      |1052.78      |1048.81     |1048.3     |2015-05-15     |2008-07-28|IPCA|2025-11-21 16:23:48|
+-----------+----------+-------------+------------+-----------+---------------+----------+----+-------------------+
only showing top 20 rows
Dados Transformados (Silver):
+-----------+----------+-------------+------------+-----------+---------------+----------+-----------+-------------------+
|CompraManha|VendaManha|PUCompraManha|PUVendaManha|PUBaseManha|Data_Vencimento|Data_Base |Tipo       |dt_update          |
+-----------+----------+-------------+------------+-----------+---------------+----------+-----------+-------------------+
|12.29      |12.32     |986.29       |986.26      |985.8      |2009-04-01     |2009-02-13|PRE-FIXADOS|2025-11-21 16:16:34|
|10.94      |11.0      |749.16       |748.03      |747.72     |2012-01-01     |2009-03-17|PRE-FIXADOS|2025-11-21 16:16:36|
|13.1       |13.13     |971.58       |971.52      |971.05     |2009-04-01     |2009-01-05|PRE-FIXADOS|2025-11-21 16:16:37|
|18.5       |18.54     |818.68       |818.36      |817.8      |2006-10-01     |2005-07-26|PRE-FIXADOS|2025-11-21 16:16:40|
|19.42      |19.45     |939.24       |939.16      |938.49     |2006-01-01     |2005-08-23|PRE-FIXADOS|2025-11-21 16:16:43|
|18.43      |18.47     |865.61       |865.36      |864.78     |2006-07-01     |2005-08-19|PRE-FIXADOS|2025-11-21 16:16:43|
|18.01      |18.05     |892.53       |892.33      |891.74     |2006-07-01     |2005-10-20|PRE-FIXADOS|2025-11-21 16:16:57|
|14.5       |14.54     |878.06       |877.77      |877.3      |2009-07-01     |2008-07-15|PRE-FIXADOS|2025-11-21 16:17:00|
|14.71      |14.75     |838.69       |838.32      |837.86     |2009-10-01     |2008-06-23|PRE-FIXADOS|2025-11-21 16:17:08|
|14.6       |14.64     |882.08       |881.8       |881.32     |2009-07-01     |2008-07-29|PRE-FIXADOS|2025-11-21 16:17:11|
|13.37      |13.43     |757.77       |756.89      |756.51     |2010-07-01     |2008-04-11|PRE-FIXADOS|2025-11-21 16:17:14|
|11.29      |11.33     |935.92       |935.71      |935.31     |2008-07-01     |2007-11-12|PRE-FIXADOS|2025-11-21 16:17:16|
|11.33      |11.37     |917.17       |916.9       |916.51     |2008-07-01     |2007-09-03|PRE-FIXADOS|2025-11-21 16:17:21|
|12.12      |12.18     |787.22       |786.34      |785.98     |2009-10-01     |2007-08-24|PRE-FIXADOS|2025-11-21 16:17:22|
|12.16      |12.21     |838.04       |837.46      |837.08     |2009-07-01     |2007-12-12|PRE-FIXADOS|2025-11-21 16:17:22|
|12.59      |12.63     |844.16       |843.73      |843.34     |2009-07-01     |2008-01-23|PRE-FIXADOS|2025-11-21 16:17:24|
|11.69      |11.73     |926.09       |925.86      |925.45     |2008-10-01     |2008-01-21|PRE-FIXADOS|2025-11-21 16:17:25|
|12.46      |12.51     |805.18       |804.52      |804.14     |2010-01-01     |2008-02-27|PRE-FIXADOS|2025-11-21 16:17:29|
|11.54      |11.58     |885.34       |884.98      |884.6      |2009-01-01     |2007-11-21|PRE-FIXADOS|2025-11-21 16:17:29|
|11.17      |11.2      |988.71       |988.69      |988.27     |2008-01-01     |2007-11-21|PRE-FIXADOS|2025-11-21 16:17:29|
+-----------+----------+-------------+------------+-----------+---------------+----------+-----------+-------------------+
only showing top 20 rows

Salvando dados no postgres

In [37]:
url = "jdbc:postgresql://localhost:5432/postgres"
tabela = "tabela_silver_ipca"
usuario = "postgres"
senha = "postgres"

df_silver_ipca.write \
    .format("jdbc") \
    .option("url", url) \
    .option("dbtable", tabela) \
    .option("user", usuario) \
    .option("password", senha) \
    .option("driver", "org.postgresql.Driver") \
    .mode("append") \
    .save()

In [38]:
url = "jdbc:postgresql://localhost:5432/postgres"
tabela = "tabela_silver_pre"
usuario = "postgres"
senha = "postgres"

df_silver_pre.write \
    .format("jdbc") \
    .option("url", url) \
    .option("dbtable", tabela) \
    .option("user", usuario) \
    .option("password", senha) \
    .option("driver", "org.postgresql.Driver") \
    .mode("append") \
    .save()

Limpando os dados para a camada Gold

In [39]:
# -----------------------
# Agregação e Métricas - Camada Gold
# -----------------------
# Calcular métricas agregadas
df_gold_ipca = df_silver_ipca.groupBy("Tipo").agg(
    avg("PUCompraManha").alias("Media_PUCompraManha"),
    avg("PUVendaManha").alias("Media_PUVendaManha"),
    count("*").alias("Total_Registros")
)

df_gold_pre = df_silver_pre.groupBy("Tipo").agg(
    avg("PUCompraManha").alias("Media_PUCompraManha"),
    avg("PUVendaManha").alias("Media_PUVendaManha"),
    count("*").alias("Total_Registros")
)

# Visualizar as métricas agregadas
print("Dados Agregados (Gold):")
df_gold_ipca.show(truncate=False)

print("Dados Agregados (Gold):")
df_gold_pre.show(truncate=False)

Dados Agregados (Gold):
+----+-------------------+------------------+---------------+
|Tipo|Media_PUCompraManha|Media_PUVendaManha|Total_Registros|
+----+-------------------+------------------+---------------+
|IPCA|1798.0110635374829 |1783.4337206639989|17470          |
+----+-------------------+------------------+---------------+

Dados Agregados (Gold):
+-----------+-------------------+------------------+---------------+
|Tipo       |Media_PUCompraManha|Media_PUVendaManha|Total_Registros|
+-----------+-------------------+------------------+---------------+
|PRE-FIXADOS|819.3224680505301  |818.1025094186302 |27074          |
+-----------+-------------------+------------------+---------------+

In [40]:
url = "jdbc:postgresql://localhost:5432/postgres"
tabela = "tabela_gold_ipca"
usuario = "postgres"
senha = "postgres"

df_gold_ipca.write \
    .format("jdbc") \
    .option("url", url) \
    .option("dbtable", tabela) \
    .option("user", usuario) \
    .option("password", senha) \
    .option("driver", "org.postgresql.Driver") \
    .mode("append") \
    .save()

In [41]:
url = "jdbc:postgresql://localhost:5432/postgres"
tabela = "tabela_gold_pre"
usuario = "postgres"
senha = "postgres"

df_gold_pre.write \
    .format("jdbc") \
    .option("url", url) \
    .option("dbtable", tabela) \
    .option("user", usuario) \
    .option("password", senha) \
    .option("driver", "org.postgresql.Driver") \
    .mode("append") \
    .save()